server:
  scheme: http
  address: localhost
  port: 18080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:dev
    username: sa
    password: 1111
#  redis:
#    host: localhost
#    port: 16379
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
decorator:
  datasource:
    p6spy:
      enable-logging: true
app:
  url: http://localhost:18080
  docsUrl: http://localhost:18080/docs/index.html
  cors:
    allowedOrigins: http://localhost:3000